site_name: Blooket X, Hack Preventer
site_url: https://www.blooketx.com/

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - toc.follow
    - toc.integrate
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - social
  - meta
  - mkdocs-video:
      css_style:
        width: "39.43vw"
        height: "22.172vw"

extra_css:
  - stylesheets/global.css

extra_javascript:
  - javascript/copy-button.js

nav:
  - Blooket X: index.md
  - Installing: installing.md
  - Creating Bookmarks: creating-bookmarks.md

repo_url: https://github.com/hostedposted/BlooketXHackPreventer
repo_name: hostedposted/BlooketXHackPreventer
